### ISSUE TITLE
errors during maven build

### ISSUE THREAD

**Issue by seralf** [LinkedDataFragments/Server.Java#34]
Hello, trying to compile the latest version of the library (in order to have it on my local maven), I had the following errors:

```
~/dev_src/LDF/Server.Java (master)
$ mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Linked Data Fragments Server 0.1.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ldfserver ---
[INFO] Deleting ~\development\Server.Java\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ldfserver ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 10 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ ldfserver ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 50 source files to ~\development\Server.Java\target\classes
[WARNING] ~/development/LDF/Server.Java/src/main/java/org/linkeddatafragments/views/HtmlTriplePatternFragmentWriterImpl.java: ~\development\Server.Java\src\main\java\org\linkeddatafragments\views\HtmlTriplePatternFragmentWriterImpl.java uses unchecked or unsafe operations.
[WARNING] ~/development/LDF/Server.Java/src/main/java/org/linkeddatafragments/views/HtmlTriplePatternFragmentWriterImpl.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ldfserver ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ ldfserver ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 4 source files to ~\development\Server.Java\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ ldfserver ---
[INFO] Surefire report directory: ~\development\Server.Java\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.linkeddatafragments.test.datasource.HdtDataSourceTest
File converted in: 955 ms 639 us
Could not read .hdt.index, Generating a new one.
Predicate Bitmap in 19 ms 809 us
Count predicates in 22 ms 495 us
Count Objects in 18 ms 469 us Max was: 8470
Bitmap in 6 ms 590 us
Object references in 41 ms 236 us
Sort object sublists in 19 ms 132 us
Count predicates in 3 ms 878 us
Index generated in 90 ms 373 us
log4j:WARN No appenders could be found for logger (org.apache.jena.riot.system.stream.JenaIOEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.875 sec
Running org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.203 sec <<< FAILURE!
org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest  Time elapsed: 0.203 sec  <<< ERROR!
com.hp.hpl.jena.tdb.TDBException: Root blocks must be at position zero (got 5120)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeNodeMgr.createEmptyBPT(BPTreeNodeMgr.java:55)
        at com.hp.hpl.jena.tdb.index.bplustree.BPlusTree.createIfAbsent(BPlusTree.java:214)
        at com.hp.hpl.jena.tdb.index.bplustree.BPlusTree.create(BPlusTree.java:140)
        at com.hp.hpl.jena.tdb.index.BuilderStdIndex$RangeIndexBuilderStd.createBPTree(BuilderStdIndex.java:94)
        at com.hp.hpl.jena.tdb.index.BuilderStdIndex$RangeIndexBuilderStd.buildRangeIndex(BuilderStdIndex.java:65)
        at com.hp.hpl.jena.tdb.setup.BuilderStdDB$TupleIndexBuilderStd.buildTupleIndex(BuilderStdDB.java:54)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.makeTupleIndex(DatasetBuilderStd.java:323)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.makeTupleIndexes(DatasetBuilderStd.java:315)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.makeTupleIndexes(DatasetBuilderStd.java:305)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.makeQuadTable(DatasetBuilderStd.java:268)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.buildWorker(DatasetBuilderStd.java:212)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd._build(DatasetBuilderStd.java:204)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.build(DatasetBuilderStd.java:193)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.create(DatasetBuilderStd.java:92)
        at com.hp.hpl.jena.tdb.StoreConnection.make(StoreConnection.java:228)
        at com.hp.hpl.jena.tdb.StoreConnection.make(StoreConnection.java:235)
        at com.hp.hpl.jena.tdb.transaction.DatasetGraphTransaction.<init>(DatasetGraphTransaction.java:75)
        at com.hp.hpl.jena.tdb.sys.TDBMaker._create(TDBMaker.java:58)
        at com.hp.hpl.jena.tdb.sys.TDBMaker.createDatasetGraphTransaction(TDBMaker.java:46)
        at com.hp.hpl.jena.tdb.TDBFactory._createDatasetGraph(TDBFactory.java:104)
        at com.hp.hpl.jena.tdb.TDBFactory.createDatasetGraph(TDBFactory.java:73)
        at com.hp.hpl.jena.tdb.TDBFactory.createDataset(TDBFactory.java:52)
        at com.hp.hpl.jena.tdb.TDBFactory.createDataset(TDBFactory.java:48)
        at org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest.setUpClass(JenaTDBDataSourceTest.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest  Time elapsed: 0.203 sec  <<< ERROR!
java.lang.NullPointerException
        at com.hp.hpl.jena.tdb.TDBFactory.location(TDBFactory.java:143)
        at com.hp.hpl.jena.tdb.TDBFactory.release(TDBFactory.java:84)
        at org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest.tearDownClass(JenaTDBDataSourceTest.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.linkeddatafragments.test.TestSuite
File converted in: 713 ms 101 us
Could not read .hdt.index, Generating a new one.
Predicate Bitmap in 6 ms 39 us
Count predicates in 10 ms 985 us
Count Objects in 7 ms 182 us Max was: 8470
Bitmap in 964 us
Object references in 42 ms 96 us
Sort object sublists in 23 ms 261 us
Count predicates in 16 ms 117 us
Index generated in 90 ms 821 us
Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.047 sec <<< FAILURE!
org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest  Time elapsed: 0.016 sec  <<< ERROR!
com.hp.hpl.jena.tdb.TDBException: Root blocks must be at position zero (got 6144)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeNodeMgr.createEmptyBPT(BPTreeNodeMgr.java:55)
        at com.hp.hpl.jena.tdb.index.bplustree.BPlusTree.createIfAbsent(BPlusTree.java:214)
        at com.hp.hpl.jena.tdb.index.bplustree.BPlusTree.create(BPlusTree.java:140)
        at com.hp.hpl.jena.tdb.index.BuilderStdIndex$RangeIndexBuilderStd.createBPTree(BuilderStdIndex.java:94)
        at com.hp.hpl.jena.tdb.index.BuilderStdIndex$RangeIndexBuilderStd.buildRangeIndex(BuilderStdIndex.java:65)
        at com.hp.hpl.jena.tdb.setup.BuilderStdDB$TupleIndexBuilderStd.buildTupleIndex(BuilderStdDB.java:54)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.makeTupleIndex(DatasetBuilderStd.java:323)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.makeTupleIndexes(DatasetBuilderStd.java:315)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.makeTupleIndexes(DatasetBuilderStd.java:305)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.makeQuadTable(DatasetBuilderStd.java:268)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.buildWorker(DatasetBuilderStd.java:212)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd._build(DatasetBuilderStd.java:204)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.build(DatasetBuilderStd.java:193)
        at com.hp.hpl.jena.tdb.setup.DatasetBuilderStd.create(DatasetBuilderStd.java:92)
        at com.hp.hpl.jena.tdb.StoreConnection.make(StoreConnection.java:228)
        at com.hp.hpl.jena.tdb.StoreConnection.make(StoreConnection.java:235)
        at com.hp.hpl.jena.tdb.transaction.DatasetGraphTransaction.<init>(DatasetGraphTransaction.java:75)
        at com.hp.hpl.jena.tdb.sys.TDBMaker._create(TDBMaker.java:58)
        at com.hp.hpl.jena.tdb.sys.TDBMaker.createDatasetGraphTransaction(TDBMaker.java:46)
        at com.hp.hpl.jena.tdb.TDBFactory._createDatasetGraph(TDBFactory.java:104)
        at com.hp.hpl.jena.tdb.TDBFactory.createDatasetGraph(TDBFactory.java:73)
        at com.hp.hpl.jena.tdb.TDBFactory.createDataset(TDBFactory.java:52)
        at com.hp.hpl.jena.tdb.TDBFactory.createDataset(TDBFactory.java:48)
        at org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest.setUpClass(JenaTDBDataSourceTest.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:24)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.NullPointerException
        at com.hp.hpl.jena.tdb.TDBFactory.location(TDBFactory.java:143)
        at com.hp.hpl.jena.tdb.TDBFactory.release(TDBFactory.java:84)
        at org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest.tearDownClass(JenaTDBDataSourceTest.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:37)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:24)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error:
  org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest: Root blocks must be at position zero (got 5120)
  org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest
  org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest: Root blocks must be at position zero (got 6144)
  org.linkeddatafragments.test.datasource.JenaTDBDataSourceTest

Tests run: 8, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.799 s
[INFO] Finished at: 2016-06-30T14:42:01+02:00
[INFO] Final Memory: 26M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ldfserver: There are test failures.
[ERROR]
[ERROR] Please refer to ~\development\Server.Java\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by mielvds** [comment]
Strange, builds fine here. 
- have you gotten the latest version?
- check your maven & java version
- @barthanssens: your TDBDatasource seems to fail, any ideas?

**Comment by barthanssens** [comment]
Hmz, builds on my system (Win10, Netbeans, JDK 8).
Some googling on "Root blocks must be at position zero" (http://stackoverflow.com/questions/24319576/jena-tdbexception-root-blocks-must-be-at-position-zero) suggests that the test datastore may not be updated correctly.

**Comment by seralf** [comment]
Hi I'm trying to compile directly from the console on windows, using both the win terminal and the mingw64 console by git.

My system configuration is the following:

```
Apache Maven 3.3.9 
Maven home: ~\sw\maven
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_92\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
```

**Comment by seralf** [comment]
HI @barthanssens thank you for the suggestion, you are right: the problem seems to be related to folders which doesn't exist yet or cannot be deleted.

running
```
mvn clean -Djava.io.tmpdir=target package
mvn -Djava.io.tmpdir=target -Dgpg.skip=true install
```
correctly creates the package or install it.
Note: I had to explicitly specify the folder where to handle the ldf-jena-test, and had to disable gpg check in the second case, in order to use install (avoiding manual local installation!).

Maybe the pre-post conditions on folders could be added directly to the test cases?

**Comment by barthanssens** [comment]
Aha, nice. For the purpose of testing, I think it would be even better to forget about disk-based storage altogether and just use an in-memory store...

**Comment by seralf** [comment]
it's possible however to provide a default folder, avoiding permissions problems on win,

I've tested with something like:

```
String tmpdirName = System.getProperty("java.io.tmpdir", "target/TEMP");
File tmpdir = new File(tmpdirName).getCanonicalFile();
if(!tmpdir.exists()) tmpdir.mkdirs(); // ensure the temp directory exists
jena = new File(tmpdir, "ldf-jena-test").getCanonicalFile();
jena.mkdir();
```
and it works from Eclipse, without having necessarily to enable a system property.
